Second task
Anton788/2019-2-Track-Frontend-A-Ilin pull request #2
Opened 2019-10-27 21:19 UTC by Anton788

2019-10-28 14:00 UTC, priver requested changes

2019-10-28 14:00 UTC, priver commented on web-components/src/components/MessageForm.js
> +      this.count = Number.parseInt(localStorage.getItem('count'), 10);
как работать с localStorage я рассказывал на семинаре

2019-10-28 14:00 UTC, priver commented on web-components/src/components/MessageForm.js
> +        const message = document.createElement('div');
нужно создать отдельный компонент для сообщения

2019-10-28 14:39 UTC, Anton788 commented on web-components/src/components/MessageForm.js
> +      this.count = Number.parseInt(localStorage.getItem('count'), 10);
А что не так? Или просто не надо вообще никогда чистить его?

2019-10-28 14:45 UTC, priver commented on web-components/src/components/MessageForm.js
> +      this.count = Number.parseInt(localStorage.getItem('count'), 10);
вот пример:
https://gist.github.com/priver/30e20aae479f96efd52497c00b70877c

2019-10-29 09:50 UTC, priver commented on web-components/src/components/MessageForm.js
> +      this.count = Number.parseInt(localStorage.getItem('count'), 10);
не вижу изменений, почему это зарезолвлено?

2019-10-29 10:50 UTC, Anton788 commented on web-components/src/components/MessageForm.js
> +      this.count = Number.parseInt(localStorage.getItem('count'), 10);
Думал, что исправил, но не сразу понял вас)

2019-10-29 13:44 UTC, Anton788 commented on web-components/src/components/MessageForm.js
> +      this.count = Number.parseInt(localStorage.getItem('count'), 10);
Исправил

2019-12-30 10:57 UTC, closed without merging